### ISSUE TITLE
sedgwick shouldnt teleport all zombies at once

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#106]
it lags a LOT when theres 200+ zombies

**Comment by Gingerbeard5773** [comment]
its also a guaranteed game end in later waves, caused by random chance. i will change it up.
as for lag, it may be caused by excessive particles that are done when the spell is cast. that or its just kag's engine being terrible at moving a bunch of blobs into people's screen all at once

**Comment by Gingerbeard5773** [comment]
completed, though instead of capping the tp amount, skelepedes will no longer be teleported. without the massive lag spike, surviving the teleports should be much more viable.
