### ISSUE TITLE
drill materials

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#114]
when mining playerbuilt blocks, ie: iron blocks, it will not give materials like a pickaxe would

**Comment by Gingerbeard5773** [comment]
this is probably because the drill has a 75% yield, and iron blocks already yield so low that it just rounds down to 0 yield

**Comment by Gingerbeard5773** [comment]
tbh not really an issue since it only matters for iron and iron doesnt give much anyways
