### ISSUE TITLE
shift + 1-9

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#117]
using the block keybinds (shift + 1-9) no longer selects the correct item like on vanilla. my shift + 5 is a spike, but gets made as a shop. likely due to having a trap block and trap bridge.

**Comment by Gingerbeard5773** [comment]
tbh fault of base kag for not using a dictionary for binds  but whatev. i can prob fix just by moving blocks around in the menu

**Comment by Gingerbeard5773** [comment]
completed. even if the bindings are wrong you can correct them with the binding menu which is now in the mod
