### ISSUE TITLE
zombies dont collide with top map border

### ISSUE THREAD

**Issue by Gingerbeard5773** [Gingerbeard5773/Zombies_Reborn#130]
maybe it would be flyers only like greg and wraith. This change would make it so walls can be scaled by zombies though, making walls less effective.

**Comment by SonantDread** [comment]
i think doing it for every zombie would be fine, people would just need to learn how to put a 4 block ledge on their walls

**Comment by Gingerbeard5773** [comment]
completed, we'll see what happens
