### ISSUE TITLE
gregs can drop players for above height limit

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#140]
it should probably just cap at world height since players cant go above it

**Comment by Gingerbeard5773** [comment]
Im confused what the issue as gregs drop players as soon as they reach world height

**Comment by Gingerbeard5773** [comment]
tried fixing this by letting players go above height limit and was met with an insanely strange bug where players collide with tiles in the map whilst outside of the map.
