### ISSUE TITLE
Maximum Character (and item) weight

### ISSUE THREAD

**Issue by RobotDerevo** [Gingerbeard5773/Zombies_Reborn#169]
Add maximum weight  for characters

Archers:
Female: 25 KG, Male: 30 KG

Builder:
Female: 30 KG, Male: 35 KG

Knight:
Female: 25KG, Male: 30 KG

OR

Archer:
25 kg

Builder:
30 kg

Knight:

27 kg

**Comment by Gingerbeard5773** [comment]
will not be done
