### ISSUE TITLE
random ideas

### ISSUE THREAD

**Issue by s1necura** [Gingerbeard5773/Zombies_Reborn#17]
Add a flight path to merchants on the remote. So that they arrive from the left or right of the event horizon, and not from outer space perpendicular down / up.

Trophies. After the death of monsters, a trophy drops out with a small chance. The trophies may disappear after a while. After picking up a trophy, it can be sold at a good price from a merchant:
Zombie Knight: Old Sword 25 coins
Greg: Heart of Stone 25 coins
Wraith, skeleton: Skull 20 coins

Enable zombies to pick up money.

Add a merchant on a donkey. Comes on foot to the player's castle.

Enable the zombie knight to throw bombs back at the player if they fall next to him.

Enable Greg to pick up keg. It'll be fun. 

Add regeneration to undisturbed blocks of earth. 

Add vanilla tunnel.

To make it possible to use corpses as a combat projectile for a catapult, similar in effect to a stone boulder. 

Add a bonfire. It illuminates well and you can fry meat or fish on it.

Lamp unit, requires a lamp. A very useful block. During the night, nothing is visible and it is necessary to illuminate the surroundings. To do this, I suggest adding a block that is conveniently located somewhere static.

A fire grenade. The return of the second vanilla bomb. Instead of an explosion, everything around is set on fire.

A crawling zombie. If you knock down a weak zombie, it could start crawling. Of course, after receiving a little damage, he immediately died.

Stone rubble. A block from the classic KAG. It is found in ruins or appears after a collapsed tower. Upon contact, it is destroyed.

Statue of Greg. A decorative element that could be used as an addition to the ruins. You can add a revival function, when a wave of zombies begins, the statue wakes up.

Grid block, requires a stone. A block that cannot be passed through, but you can shoot or throw objects through it. It could be used as an addition to the ruins.

Add migrants. Take a tax on their earned money. After death, the player could be reborn in their place. Use them to protect the castle, giving the opportunity to choose the right class and order to patrol the territory. To order to perform simple actions: to dig a stone, a tree, to produce food by growing harvest.

Add various potions with temporary effect. During the action of the potion, the player emits particles, and also next to his health there is an icon of the effect and the duration of the action. Basically, they make modifications by increasing the standard characteristics. 
New items:
 1. Medicinal ointment 155 coins. Restores 3 hp for some time. If you take damage, the effect of the treatment will be canceled. 
 2. Health potion 385 coins. The magical properties of this potion will make you fresher! Within 5 minutes, gives + 1 health point.
 3. Power potion 325 coins. Your punches will be overflowing with power! For 3 minutes, gives +1 damage.
 4. Speed potion 275 coins. The energy of this drink helps to cheer up! For 2 minutes, gives +25% to the attack speed and movement.

Add an analogy to gold - crystals. Thanks to crystals, buy rare items or create new ones.

Add weather effects. Rain, thunderstorm, morning fog, bright night, strong wind. During a thunderstorm, lightning could randomly fall on the map, illuminating the entire map and setting fire to the block. A strong wind could slowly push aside all objects.

**Comment by Gingerbeard5773** [comment]
many of these ideas have been implemented. any decent remaining ideas are already in other issues. the rest will not be done. closing
