### ISSUE TITLE
Bosses

### ISSUE THREAD

**Issue by RobotDerevo** [Gingerbeard5773/Zombies_Reborn#179]
Add bosses 3 Types

Skeleton boss, spawns on 10 day
Spawns many skeletons around himself and attacks with wraiths.

Zombie Boss spawns on 20 day
Spawns many zombies and bombs with bodies of migrants.

DEMON (Finall boss) spawns on 40 day
Spawns zombie knights, necromancers (5), wraiths and worms(3).

**Comment by Gingerbeard5773** [comment]
put them in #20
