### ISSUE TITLE
buff steel armor

### ISSUE THREAD

**Issue by karasik112** [Gingerbeard5773/Zombies_Reborn#184]
if you wearing a full steel set then you will be immune to fire

**Comment by AlexWHite004** [comment]
This leads to the realism problem: the armor will literally turn into a boiling pot, and you will become a boiled krill. Then there are next things: either add a heat bar that fills up whenever a person stays too long in fire, and when on MAX, damages him, or add a chemsuit, like in TC, to protect from fire (can be an armor equivalent too).

**Comment by karasik112** [comment]
> This leads to the realism problem: the armor will literally turn into a boiling pot, and you will become a boiled krill. Then there are next things: either add a heat bar that fills up whenever a person stays too long in fire, and when on MAX, damages him, or add a chemsuit, like in TC, to protect from fire (can be an armor equivalent too).

steel armor just too weak and not worth it, and i dont think that we need some new useless mechanic like heat bar

**Comment by AlexWHite004** [comment]
But fire protection barely makes any sense. It's easier to just make it work as a health booster than just that

**Comment by karasik112** [comment]
> But fire protection barely makes any sense. It's easier to just make it work as a health booster than just that

its doesnt need to make sense. its a game with zombies, im just want to buff steel armor somehow

**Comment by AlexWHite004** [comment]
If it's just a game, why you're not my big titty zombie skeletaur girlfriend? Some things must have sense, no matter what. Mo' health it is

**Comment by karasik112** [comment]
> If it's just a game, why you're not my big titty zombie skeletaur girlfriend? Some things must have sense, no matter what. Mo' health it is

what???

**Comment by AlexWHite004** [comment]
You're blushing?????

**Comment by Gingerbeard5773** [comment]
technology for fireproof armor?

**Comment by karasik112** [comment]
> technology for fireproof armor?

i think it would be some good balance but where you gonna put it in tech tree?

**Comment by Gingerbeard5773** [comment]
resolved
