### ISSUE TITLE
Add Cannons

### ISSUE THREAD

**Issue by TC-DarkSlayer** [Gingerbeard5773/Zombies_Reborn#187]
- Explosive cannon
- Cannon that shoots a projectile similar to a boulder, but it deals crushing damage as it mows zombie knights
- Incendiary cannon: Explosive cannon but flames. Less explosive damage
- It'll be stationary like the mounted bow, so that you could attach it on bombers or tanks

**Comment by Ctaehko** [comment]
+1
Though, why an incendiary cannon and not a molotov shell?

**Comment by Gingerbeard5773** [comment]
issue already exists
