### ISSUE TITLE
Index Of bound Call Stack to emotes

### ISSUE THREAD

**Issue by RobotDerevo** [Gingerbeard5773/Zombies_Reborn#194]
![изображение](https://github.com/user-attachments/assets/2154afbb-9eb9-47b9-8b29-7ff8caafcd77)
Fix that shit

**Comment by RobotDerevo** [comment]
In solo

**Comment by Gingerbeard5773** [comment]
I cant fix something I cant replicate. this mod doesn't even touch that script, this is your own issue i think because i've never seen this before. Its possible it is a base issue and not a mod problem
