### ISSUE TITLE
Reworked trader

### ISSUE THREAD

**Issue by Gingerbeard5773** [Gingerbeard5773/Zombies_Reborn#29]
Instead of a basic shop, selling items would be more like a pawn-shop in that the trader would give you a price for any item you have. All kag items would be given a basic price multiplied by its quantity.

**Comment by TC-DarkSlayer** [comment]
const string[] itemName and const int[] value then for loop the stuff
Store button and inventory. Then a sell all items button checks all items in its inventory and server_Die() each one but adds their value before doing so. Sets the player's coins to the amount.
If trader starts to leave, (Could drop all items or RUNS AWAY WITH THE MATS HAHA skill issue)
Then if it doesn't know what the item is (not listed in the array) then item is not sold and is dropped on the ground.

**Comment by Gingerbeard5773** [comment]
the original plan was to add in an additional menu that has the player's inventory, then the player can choose what to sell from their inventory just by clicking on their items

**Comment by Gingerbeard5773** [comment]
No longer planning on doing this
