### ISSUE TITLE
archer buff

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#58]
no sane human being plays this class

**Comment by Gingerbeard5773** [comment]
but how though??? theres just no good way since the archers dont specialize in crowd control

**Comment by Gingerbeard5773** [comment]
1: replace fire arrows with molotov arrows
2: add in firework arrows
3: buff water considerably by being able to stun all zombies for a lengthy time

**Comment by Gingerbeard5773** [comment]
completed
