### ISSUE TITLE
skelepede voiding items

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#77]
should all my items be voided when i die? if thats the intended behavior feel free to close this issue.

**Comment by Gingerbeard5773** [comment]
it is intended behavior. though, skelepedes are OP and people have been complaining about them, so perhaps there is discussion to be had about nerfing them or adding new ways to counter them.

**Comment by SonantDread** [comment]
closing. skelepedes are mostly fine in their current state.
